[tox]
envlist = py310,py311,py312,py313
requires = tox-uv

[testenv]
changedir = .tox
dependency_groups = dev
commands =
	coverage run --parallel --rcfile {toxinidir}/.tox-coveragerc -m pytest {posargs} {envsitepackagesdir}/lithoxyl/tests/

[testenv:coverage-report]
changedir = .tox
depends = py310,py311,py312,py313
dependency_groups = dev
commands =
	coverage combine --rcfile {toxinidir}/.tox-coveragerc
	coverage xml --rcfile {toxinidir}/.tox-coveragerc -o {toxinidir}/.tox/coverage.xml
	coverage report --rcfile {toxinidir}/.tox-coveragerc
	coverage html --rcfile {toxinidir}/.tox-coveragerc -d {toxinidir}/htmlcov
