name: Tests
on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: Linux, python: "3.13", os: ubuntu-latest, tox: py313 }
          - { name: Windows, python: "3.13", os: windows-latest, tox: py313 }
          - { name: Mac, python: "3.13", os: macos-latest, tox: py313 }
          - { name: "3.12", python: "3.12", os: ubuntu-latest, tox: py312 }
          - { name: "3.11", python: "3.11", os: ubuntu-latest, tox: py311 }
          - { name: "3.10", python: "3.10", os: ubuntu-latest, tox: py310 }
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: uvx --with tox-uv tox -e ${{ matrix.tox }}
      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: .tox/coverage-${{ matrix.tox }}.xml
          token: ${{ secrets.CODECOV_TOKEN }}
